from django.db import models
from django.utils import timezone
from Project.models import *
from Team.models import *
from category.models import *
from Files.models import *


class Task(models.Model):
    title = models.CharField(max_length=50,null=True)
    description = models.TextField(null=True)
    start_date = models.DateField(null=True)
    due_date = models.DateField(null=True)
    current_date = models.DateField(default=timezone.now)
    priority = models.CharField(max_length=100)
    project = models.ForeignKey(Projects,on_delete=models.CASCADE,null=True)
    category = models.CharField(max_length=100,null=True)
    file = models.ManyToManyField(UploadFile,blank=True)
    status = models.CharField(max_length=100,null=True)
    staff = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='+')
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True)
    assigned_staff = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='+')
    created_by = models.ForeignKey(Register,on_delete=models.CASCADE,null=True)
    parent_task = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='child_tasks')
    
# class SubTask(models.Model):
#     task = models.ForeignKey(Task,on_delete=models.CASCADE,null=True)
#     title = models.CharField(max_length=50,null=True)
#     description = models.TextField(null=True)
#     start_date = models.DateField(null=True)
#     due_date = models.DateField(null=True)
#     current_date = models.DateField(default=timezone.now)
#     priority = models.CharField(max_length=100)
#     project = models.ForeignKey(Projects,on_delete=models.CASCADE,null=True)
#     category = models.CharField(max_length=100,null=True)
#     file = models.ManyToManyField(UploadFile,blank=True)
#     status = models.CharField(max_length=100,null=True)
#     staff = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='+')
#     team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True)
#     assigned_staff = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='+')
#     created_by = models.ForeignKey(Register,on_delete=models.CASCADE,null=True)

# class ProjectHistory(models.Model):
#     project = models.ForeignKey(Projects, on_delete=models.CASCADE)
#     modified_by = models.ForeignKey(Register, on_delete=models.CASCADE)
#     modified_date = models.DateTimeField(default=timezone.now)
#     old_title = models.CharField(max_length=50, null=True)
#     new_title = models.CharField(max_length=50, null=True)
#     old_description = models.TextField(null=True)
#     new_description = models.TextField(null=True)
#     old_start_date = models.DateField(null=True)
#     new_start_date = models.DateField(null=True)
#     old_due_date = models.DateField(null=True)
#     new_due_date = models.DateField(null=True)
#     new_current_date = models.DateField(null=True)
#     old_team_members = models.ManyToManyField(Register, related_name='project_history_old_team_members',blank=True)
#     new_team_members = models.ManyToManyField(Register, related_name='project_history_new_team_members',blank=True)
#     team_members_add_status = models.TextField(null=True)
#     team_members_delete_status = models.TextField(null=True)
#     old_team_name = models.CharField(max_length=50, null=True)
#     new_team_name = models.CharField(max_length=50, null=True)
#     old_files = models.TextField(null=True)
#     new_files = models.TextField(null=True)
#     file_status = models.TextField(null=True)
#     file_remove_status = models.TextField(null=True)
#     task_add = models.TextField(null=True)
#     task_delete = models.TextField(null=True)
#     task = models.TextField(null=True)
    
class TaskHistory(models.Model):
    project = models.ForeignKey(Projects,on_delete=models.CASCADE,null=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True)
    modified_by = models.ForeignKey(Register,on_delete=models.CASCADE,null=True, related_name='+')
    modified_at = models.DateTimeField(default=timezone.now)
    old_title = models.TextField(max_length=50,null=True)
    new_title = models.TextField(max_length=50,null=True)
    old_description = models.TextField(null=True)
    new_description = models.TextField(null=True)
    old_start_date = models.DateField(null=True)
    new_start_date = models.DateField(null=True)
    old_due_date = models.DateField(null=True)
    new_due_date = models.DateField(null=True)
    old_priority = models.TextField(null=True)
    new_priority = models.TextField(null=True)
    old_category = models.TextField(null=True)
    new_category = models.TextField(null=True)
    old_status = models.TextField(null=True)
    new_status = models.TextField(null=True)
    old_staff = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='+')
    new_staff = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='+')
    subtask_add = models.TextField(null=True)
    subtask_delete = models.TextField(null=True)
    subtask = models.TextField(null=True)
    file_status = models.TextField(null=True)
    file_remove_status = models.TextField(null=True)
    message = models.TextField(null=True)
    message_files = models.ManyToManyField(UploadFile)