# Generated by Django 4.1.4 on 2023-10-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
