# Generated by Django 4.1.4 on 2023-10-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
