# Generated by Django 4.1.4 on 2023-10-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0004_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
