# Generated by Django 4.1.4 on 2023-10-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='statuses',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
