# Generated by Django 4.1.4 on 2023-10-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_task_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='messages',
            field=models.TextField(null=True),
        ),
    ]
