# Generated by Django 4.1.4 on 2023-10-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_task_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='projectstatus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
