# Generated by Django 4.1.4 on 2023-10-30 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0005_task_projectstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
        migrations.AddField(
            model_name='task',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
