# Generated by Django 4.1.4 on 2023-10-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0007_initial'),
        ('Tasks', '0006_remove_task_team_task_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='staff',
        ),
        migrations.AddField(
            model_name='task',
            name='team_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.team_members'),
        ),
    ]
