# Generated by Django 4.1.4 on 2023-10-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0007_initial'),
        ('Tasks', '0007_remove_task_staff_task_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.teams'),
        ),
    ]
