# Generated by Django 4.1.4 on 2023-10-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_alter_task_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team_members',
        ),
    ]
