# Generated by Django 4.1.4 on 2023-11-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0010_task_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='staf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
