# Generated by Django 4.1.4 on 2023-11-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0007_initial'),
        ('Tasks', '0011_task_staf'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.teams'),
        ),
    ]
