# Generated by Django 4.1.4 on 2023-11-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0013_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='staf',
        ),
    ]
