# Generated by Django 4.1.4 on 2023-11-04 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0015_task_assigned_staff_alter_task_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='statuses',
            new_name='status',
        ),
    ]
