# Generated by Django 4.1.4 on 2023-11-07 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0045_remove_projects_old_current_date_and_more'),
        ('Team', '0007_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Files', '0006_remove_uploadfile_project'),
        ('Tasks', '0016_rename_statuses_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('messages', models.TextField(null=True)),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ManyToManyField(blank=True, to='Files.uploadfile')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projects')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.task')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.teams')),
            ],
        ),
    ]
