# Generated by Django 4.1.4 on 2023-11-08 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0006_remove_uploadfile_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0048_projecthistory_new_files_projecthistory_old_files'),
        ('Tasks', '0018_remove_subtask_messages_remove_task_messages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_title', models.TextField(max_length=50, null=True)),
                ('new_title', models.TextField(max_length=50, null=True)),
                ('old_description', models.TextField(null=True)),
                ('new_description', models.TextField(null=True)),
                ('old_start_date', models.DateField(null=True)),
                ('new_start_date', models.DateField(null=True)),
                ('old_due_date', models.DateField(null=True)),
                ('new_due_date', models.DateField(null=True)),
                ('old_priority', models.TextField(null=True)),
                ('new_priority', models.TextField(null=True)),
                ('old_category', models.TextField(null=True)),
                ('new_category', models.TextField(null=True)),
                ('old_status', models.TextField(null=True)),
                ('new_status', models.TextField(null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_file', models.ManyToManyField(blank=True, to='Files.uploadfile')),
                ('new_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('old_file', models.ManyToManyField(blank=True, related_name='+', to='Files.uploadfile')),
                ('old_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projects')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.task')),
            ],
        ),
    ]
