# Generated by Django 4.1.4 on 2023-11-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0019_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='subtask_add',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='subtask_delete',
            field=models.TextField(null=True),
        ),
    ]
