# Generated by Django 4.1.4 on 2023-11-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0021_projecthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthistory',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
