# Generated by Django 4.1.4 on 2023-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0022_alter_projecthistory_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='subtask',
            field=models.TextField(null=True),
        ),
    ]
