# Generated by Django 4.1.4 on 2023-11-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0008_team'),
        ('Tasks', '0023_taskhistory_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.team'),
        ),
    ]
