# Generated by Django 4.1.4 on 2023-11-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0024_alter_subtask_team_alter_task_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthistory',
            name='new_team',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='old_team',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='team',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
    ]
