# Generated by Django 4.1.4 on 2023-11-13 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0008_team'),
        ('Tasks', '0025_remove_projecthistory_new_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='new_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_history_new_team', to='Team.team_members'),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_history_old_team', to='Team.team_members'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.teams'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.teams'),
        ),
    ]
