# Generated by Django 4.1.4 on 2023-11-14 03:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0027_alter_projecthistory_new_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthistory',
            name='new_team',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='old_team',
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='new_team_members',
            field=models.ManyToManyField(related_name='project_history_new_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='new_team_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_team_members',
            field=models.ManyToManyField(related_name='project_history_old_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_team_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
