# Generated by Django 4.1.4 on 2023-11-14 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0028_remove_projecthistory_new_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthistory',
            name='new_team_members',
            field=models.ManyToManyField(blank=True, related_name='project_history_new_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecthistory',
            name='old_team_members',
            field=models.ManyToManyField(blank=True, related_name='project_history_old_team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
