# Generated by Django 4.1.4 on 2023-11-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0029_alter_projecthistory_new_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='team_members_add_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='team_members_delete_status',
            field=models.TextField(null=True),
        ),
    ]
