# Generated by Django 4.2.7 on 2023-11-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0030_projecthistory_team_members_add_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='new_file',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='old_file',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='new_files',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='old_files',
            field=models.TextField(null=True),
        ),
    ]
