# Generated by Django 4.2.7 on 2023-11-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0006_remove_uploadfile_project'),
        ('Tasks', '0031_remove_taskhistory_new_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='new_files',
            new_name='file_remove_status',
        ),
        migrations.RenameField(
            model_name='taskhistory',
            old_name='old_files',
            new_name='file_status',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='new_file',
            field=models.ManyToManyField(blank=True, to='Files.uploadfile'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='old_file',
            field=models.ManyToManyField(blank=True, related_name='+', to='Files.uploadfile'),
        ),
    ]
