# Generated by Django 4.2.7 on 2023-11-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0032_rename_new_files_taskhistory_file_remove_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='new_file',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='old_file',
        ),
    ]
