# Generated by Django 4.2.7 on 2023-11-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0033_remove_taskhistory_new_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
