# Generated by Django 4.2.7 on 2023-11-15 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0055_remove_projects_team1_alter_projects_team'),
        ('Tasks', '0034_delete_taskhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_title', models.TextField(max_length=50, null=True)),
                ('new_title', models.TextField(max_length=50, null=True)),
                ('old_description', models.TextField(null=True)),
                ('new_description', models.TextField(null=True)),
                ('old_start_date', models.DateField(null=True)),
                ('new_start_date', models.DateField(null=True)),
                ('old_due_date', models.DateField(null=True)),
                ('new_due_date', models.DateField(null=True)),
                ('old_priority', models.TextField(null=True)),
                ('new_priority', models.TextField(null=True)),
                ('old_category', models.TextField(null=True)),
                ('new_category', models.TextField(null=True)),
                ('old_status', models.TextField(null=True)),
                ('new_status', models.TextField(null=True)),
                ('subtask_add', models.TextField(null=True)),
                ('subtask_delete', models.TextField(null=True)),
                ('subtask', models.TextField(null=True)),
                ('file_status', models.TextField(null=True)),
                ('file_remove_status', models.TextField(null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('old_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projects')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.task')),
            ],
        ),
    ]
