# Generated by Django 4.2.7 on 2023-11-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0035_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='ProjectHistory',
        ),
    ]
