# Generated by Django 4.2.7 on 2023-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0006_remove_uploadfile_project'),
        ('Tasks', '0036_taskhistory_message_delete_projecthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='message_files',
            field=models.ManyToManyField(to='Files.uploadfile'),
        ),
    ]
