# Generated by Django 4.1.4 on 2023-11-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0038_task_parent_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
