# Generated by Django 4.1.4 on 2023-10-13 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasks', '0002_task_file'),
        ('Files', '0005_alter_uploadfile_file'),
        ('Project', '0018_rename_files_projects_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.ManyToManyField(to='Files.uploadfile')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projects')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.task')),
            ],
        ),
    ]
