# Generated by Django 4.1.4 on 2023-10-16 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Status', '0003_status_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='staff',
        ),
        migrations.AddField(
            model_name='status',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
