# Generated by Django 4.1.4 on 2023-10-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Status', '0004_remove_status_staff_status_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
