# Generated by Django 4.1.4 on 2023-11-04 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0016_rename_statuses_task_status'),
        ('Status', '0005_status_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Tasks.task'),
        ),
    ]
