# Generated by Django 4.1.4 on 2023-11-09 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0019_taskhistory'),
        ('Project', '0048_projecthistory_new_files_projecthistory_old_files'),
        ('Files', '0006_remove_uploadfile_project'),
        ('Status', '0007_remove_status_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtaskmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.ManyToManyField(blank=True, to='Files.uploadfile')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projects')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Tasks.task')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
