# Generated by Django 4.1.4 on 2023-10-09 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='currentdate',
            new_name='current_date',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='enddate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='startdate',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='projects',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
