# Generated by Django 4.1.4 on 2023-10-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_projects_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
