# Generated by Django 4.1.4 on 2023-10-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_alter_projects_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='team',
        ),
    ]
