# Generated by Django 4.1.4 on 2023-10-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_alter_projects_description_alter_projects_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(default='NULL', null=True, upload_to=''),
        ),
    ]
