# Generated by Django 4.1.4 on 2023-10-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0003_initial'),
        ('Project', '0014_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='files',
            field=models.ManyToManyField(blank=True, to='Files.uploadfile'),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
