# Generated by Django 4.1.4 on 2023-10-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_projects_files_delete_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='file_paths',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
