# Generated by Django 4.1.4 on 2023-10-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_projects_file_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='file_paths',
        ),
    ]
