# Generated by Django 4.1.4 on 2023-10-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0019_projects_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='team',
        ),
    ]
