# Generated by Django 4.1.4 on 2023-10-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0007_initial'),
        ('Project', '0020_remove_projects_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.team_members'),
        ),
    ]
