# Generated by Django 4.1.4 on 2023-11-06 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0022_statusupdation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projects')),
            ],
        ),
        migrations.DeleteModel(
            name='StatusUpdation',
        ),
    ]
