# Generated by Django 4.1.4 on 2023-11-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0024_projectchangehistory_updated_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectChangeHistory',
        ),
    ]
