# Generated by Django 4.1.4 on 2023-11-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0026_projects_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects_changes',
            old_name='current_date',
            new_name='update_date',
        ),
    ]
