# Generated by Django 4.1.4 on 2023-11-06 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0027_rename_current_date_projects_changes_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_changes',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projects'),
        ),
    ]
