# Generated by Django 4.1.4 on 2023-11-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0028_projects_changes_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_changes',
            name='update_message',
            field=models.TextField(null=True),
        ),
    ]
