# Generated by Django 4.1.4 on 2023-11-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0030_projecthistory_delete_projects_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='staff',
            new_name='created_by',
        ),
    ]
