# Generated by Django 4.1.4 on 2023-11-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0031_rename_staff_projects_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectHistory',
        ),
    ]
