# Generated by Django 4.1.4 on 2023-11-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0033_projecthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthistory',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='title',
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='new_current_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='new_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='new_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='new_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='new_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_current_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
