# Generated by Django 4.1.4 on 2023-11-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0034_remove_projecthistory_current_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='old_current_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='old_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='old_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='old_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='old_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
