# Generated by Django 4.1.4 on 2023-11-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0035_projects_old_current_date_projects_old_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthistory',
            name='old_current_date',
        ),
    ]
