# Generated by Django 4.1.4 on 2023-11-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0036_remove_projecthistory_old_current_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectHistory',
        ),
    ]
