# Generated by Django 4.1.4 on 2023-11-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0042_projecthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectHistory',
        ),
    ]
