# Generated by Django 4.1.4 on 2023-11-07 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0043_delete_projecthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_title', models.CharField(max_length=50, null=True)),
                ('new_title', models.CharField(max_length=50, null=True)),
                ('old_description', models.TextField(null=True)),
                ('new_description', models.TextField(null=True)),
                ('old_start_date', models.DateField(null=True)),
                ('new_start_date', models.DateField(null=True)),
                ('old_due_date', models.DateField(null=True)),
                ('new_due_date', models.DateField(null=True)),
                ('new_current_date', models.DateField(null=True)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projects')),
            ],
        ),
    ]
