# Generated by Django 4.1.4 on 2023-11-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0044_projecthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='old_current_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='old_description',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='old_due_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='old_start_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='old_title',
        ),
    ]
