# Generated by Django 4.1.4 on 2023-11-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0007_initial'),
        ('Files', '0006_remove_uploadfile_project'),
        ('Project', '0045_remove_projects_old_current_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='new_files',
            field=models.ManyToManyField(blank=True, related_name='project_history_new_files', to='Files.uploadfile'),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='new_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_history_new_team', to='Team.team_members'),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_files',
            field=models.ManyToManyField(blank=True, related_name='project_history_old_files', to='Files.uploadfile'),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='old_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_history_old_team', to='Team.team_members'),
        ),
    ]
