# Generated by Django 4.1.4 on 2023-11-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0048_projecthistory_new_files_projecthistory_old_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='file_status',
            field=models.TextField(null=True),
        ),
    ]
