# Generated by Django 4.1.4 on 2023-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0049_projecthistory_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='file_remove_status',
            field=models.TextField(null=True),
        ),
    ]
