# Generated by Django 4.1.4 on 2023-11-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0050_projecthistory_file_remove_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthistory',
            name='task_add',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='task_delete',
            field=models.TextField(null=True),
        ),
    ]
