# Generated by Django 4.1.4 on 2023-11-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0051_projecthistory_task_add_projecthistory_task_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectHistory',
        ),
    ]
