# Generated by Django 4.1.4 on 2023-11-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0008_team'),
        ('Project', '0054_projects_team1_alter_projects_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='team1',
        ),
        migrations.AlterField(
            model_name='projects',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.team'),
        ),
    ]
