# Generated by Django 4.1.4 on 2023-10-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_members',
            name='team',
        ),
        migrations.AddField(
            model_name='team_members',
            name='team',
            field=models.ManyToManyField(to='Team.teams'),
        ),
    ]
