# Generated by Django 4.1.4 on 2023-10-10 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Team', '0003_remove_team_members_team_team_members_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_members',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team_members',
            name='team_members',
        ),
        migrations.AddField(
            model_name='team_members',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.teams'),
        ),
        migrations.AddField(
            model_name='team_members',
            name='team_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
