# Generated by Django 4.1.4 on 2023-10-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_remove_projects_team'),
        ('Team', '0005_remove_team_members_team_members_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team_members',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
