# Generated by Django 4.1.4 on 2023-11-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0009_delete_team_members_delete_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
