# Generated by Django 4.2.4 on 2023-10-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_register_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='examstatus',
        ),
    ]
