# Generated by Django 4.1.4 on 2023-10-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_register_examstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='register',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='qualification',
        ),
    ]
