# Generated by Django 4.1.4 on 2023-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_remove_register_address_remove_register_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
